### ISSUE TITLE
Element extensions not applied within shadow roots

### ISSUE THREAD

**Issue by calebdwilliams** [ungap/custom-elements-builtin#16]
@andyricchuiti and I stumbled on a use case where attempting to use an extended built-in inside of a shadow root will not apply the custom element behavior. We have a [minimal reproduction on CodePen](https://codepen.io/andyric/pen/MWwezWZ). A bit of a note on the demo, by default `LitElement` attaches a shadow root; however, using the `createRenderRoot` you can turn this behavior off. As a result, the `RootApp` element will execute the custom element script where as the `MyApp` class will not.

I believe the issue comes from [these lines](https://github.com/ungap/custom-elements-builtin/blob/master/index.js#L33-L46) where a `MutationObserver` is attached only to `document`. As a fix, this same observer should be added to all shadow roots as well (probably by monkey patching `attachShadow`).

I would be happy to take a stab at a fix if needed.

**Comment by WebReflection** [comment]
Thanks for filing the issue with an example. As I don't care much about crawling internals of third parts libraries, it'd be very useful to understand this bug in isolation, so that I can fork the code pen and use it as regression test reference.

In few words: could you please write the same example without using LitElement, or even any of my libraries, for what it matters?

Just plain Custom Elements, so that I know what to test/debug/verify/patch.

Thanks in advance for your collaboration.

**Comment by calebdwilliams** [comment]
Absolutely, not much different, but I appreciate your concern for keeping it minimal: https://codepen.io/andyric/pen/MWwezWZ

**Comment by calebdwilliams** [comment]
Here's the vanilla reproduction:

https://codepen.io/calebdwilliams/pen/YzXGXxK

**Comment by WebReflection** [comment]
This should've been fixed in `0.3.0`, please let me know if that's not the case 👋

**Comment by ghost** [comment]
@WebReflection thanks so much for looking into this. it worked!!

@calebdwilliams thanks for posting while i couldn't log in to github
