### ISSUE TITLE
Custom variable is undefined in safari

### ISSUE THREAD

**Issue by 1aron** [ungap/custom-elements-builtin#6]
```js
class MyButton extends HTMLButtonElement {
  connectedCallback() {
    this.sayHello(); // print: sayHello is undefined 
  }
  sayHello() {
    console.log('hello world');
  }
}
```

**Comment by WebReflection** [comment]
does this live test page work? https://ungap.github.io/custom-elements-builtin/test/

**Comment by 1aron** [comment]
Sorry, let me correct my question. 
The custom method is fine but the custom variable is undefined.
I forked your codepen：https://codepen.io/Aoyue/pen/ExYqYaJ
You can try it.

<img width="636" alt="螢幕快照 2019-10-02 上午1 29 33" src="https://user-images.githubusercontent.com/33840671/65985354-2a833980-e4b4-11e9-93b6-e00b7bcc28ca.png">

I'm using typescript.

**Comment by WebReflection** [comment]
So, to start with, `constructor() { super(); }` is an anti pattern, just don't write it, especially in here where there are well known [constructor caveats](https://github.com/ungap/custom-elements-builtin#constructor-caveat).

Any property that is setup at constructor time is part of the caveat, so that you need to use the suggested workaround if you want properties or setup per each instance.

As summary, **two alternatives** here:

### use defaults as prototype getters

```js
class SelectBox extends HTMLSelectElement {

  get variable() { return '123'; };

  connectedCallback() {
    this.method();
    console.log(this.variable, 'is undefined in safari');
  }
  
  method() {
    console.log('method is fine.')
  }

}
```

### use the suggested caveats workaround

```js
const init = new WeakSet;
const setup = element => {
  if (init.has(element)) return;
  element.variable = '123';
};
class SelectBox extends HTMLSelectElement {
 
  connectedCallback() {
    setup(this);
    this.method();
    console.log(this.variable, 'is undefined in safari');
  }
  
  method() {
    console.log('method is fine.')
  }

}

customElements.define('select-box', SelectBox, {extends: 'select'});
```

I am closing this, as there's nothing I can do to fix this issue.

**Comment by WebReflection** [comment]
P.S. reason there's nothing I can do, is that classes don't expose those properties via any reflection API, so it's impossible to know which property goes where or if there is a property at all that would be assigned to the instance, once constructed.

About the anti-pattern, the default no-op constructor is this `constructor(...args) { super(...args); }` but it's completely pointless to write empty constructors in general, since ever, in JS.

Omitting it, when it doesn't need to do anything, is the best way to go for both performance, transpilers, etc.

**Comment by 1aron** [comment]
@WebReflection Is this helpful?

https://github.com/jarradseers/extends-classes
